#!/bin/bash

readonly cmd=${0}
readonly cmd_name=${cmd##*/}
readonly cmd_path=${cmd%${cmd_name}}

echo -e "Welcome to git-shell! Available commands:\n"

for current_cmd in $(find ${cmd_path} -type f |sort); do
  if [[ -f "${current_cmd}" ]] && [[ -x "${current_cmd}" ]]; then
    echo "${current_cmd##*/}"
  fi
done
