#!/bin/bash

readonly cmd=${0}
readonly cmd_name=${cmd##*/}


create_repository()
{
  local repository="${1}"
  mkdir -p "${repository}" \
    && git --bare init "${repository}" > /dev/null \
    && echo "Created \"${repository##*/}\"." \
            "Use \"git clone ${USER}@${HOSTNAME}:${repository##${HOME}/}\""
}

normalize_name()
{
  local repository="${1}"
  echo "${repository%.git}.git"
}

main()
{
  if [[ ${#} -gt 0 ]]; then
    for name in ${@}; do
      local repository="$(normalize_name ${name})"
      if [[ -e "${repository}" ]]; then
        echo "Repository \"${repository}\" already exists!"
      else
        create_repository "${repository}"
      fi
    done
  else
      echo "At least one repo must be provided"
  fi
}

main "${@}"
