#!/bin/bash

export DOCKER_CLI_EXPERIMENTAL=enabled

# Download buildx plugin (not available in github environment)
mkdir -p ~/.docker/cli-plugins \
  && curl \
    --silent \
    --location \
    --output ~/.docker/cli-plugins/docker-buildx \
    https://github.com/docker/buildx/releases/download/${BUILDX_VER}/buildx-${BUILDX_VER}.linux-amd64 \
  && chmod +x ~/.docker/cli-plugins/docker-buildx

# Register binfmt_misc interpreters
docker run \
  --rm \
  --privileged \
  docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3

docker buildx create \
  --use \
  --name multiarch
