#!/bin/bash

source .git-shell  # GIT_STORAGE_PATH

readonly cmd=${0}
readonly cmd_name=${cmd##*/}


create_repository()
{
  local repository="${1}"
  mkdir -p "${repository}" \
    && git --bare init ${repository} > /dev/null \
    && echo "Created \"${repository##*/}\"." \
            "Use \"git clone ${USER}@${HOSTNAME}:${repository}\""
}

normalize_path()
{
  local repository="${1}"
  local repo_without_prefix="${repository#${GIT_STORAGE_PATH}/}"
  local repo_name_we="${repo_without_prefix%.git}"
  echo "${GIT_STORAGE_PATH}/${repo_name_we}.git"
}

main()
{
  if [[ ${#} -gt 0 ]]; then
    for name in ${@}; do
      local repository="$(normalize_path ${name})"
      if [[ -e "${repository}" ]]; then
        echo "Repository \"${repository}\" already exists!"
      else
        create_repository "${repository}"
      fi
    done
  else
      echo "At least one repo must be provided"
  fi
}

main "${@}"
