#!/bin/bash

source .git-shell
# GIT_STORAGE_PATH

readonly cmd=${0}
readonly cmd_name=${cmd##*/}


create_repository()
{
  local repository="${1}"
  local repository_name=${repository##*/}
  mkdir -p "${repository}" \
    && git --bare init ${repository} > /dev/null \
    && echo "Created \"${repository_name}\"." \
            "Use \"git clone ${USER}@${HOSTNAME}:${repository}\""
}

normalize_name()
{
  if [[ -n "${1}" ]]; then
    local repository="${1}"
    local repo_without_prefix="${repository#${GIT_STORAGE_PATH}/}"
    local repo_name_we="${repo_without_prefix%.git}"
    echo "${GIT_STORAGE_PATH}/${repo_name_we}.git"
  fi
}

main()
{
  local repository="$(normalize_name ${1})"
  if [[ -z "${repository}" ]]; then
    echo -e "\n\tUsage: ${cmd_name} <project.git>\n"
  elif [[ -e "${repository}" ]]; then
    echo "Repository \"${repository}\" already exists!"
  else
    create_repository "${repository}"
  fi
}

main "${@}"
