name: docker-buildx

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  main:
    name: build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: 1nfiniteloop/git-remote
          # ref: https://github.com/crazy-max/ghaction-docker-meta
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      # ref: https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # ref: https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#-use-an-external-cache-source-for-a-build---cache-from
          cache-from: type=registry,ref=1nfiniteloop/git-remote:latest
          cache-to: type=inline
